import "./globals.css";
import type { Metadata } from "next";

import Headerr from "@/components/header";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="pt-BR">
      <body>
      <Headerr/>
        {children}
      </body>
    </html>
  );
}
